### ISSUE TITLE
Licensing this repo

### ISSUE THREAD

**Issue by cdo256** [ryanprior/guix-packages#8]
Hi,

I'm a new Guix contributor looking to add Hugo upstream. I see you've done a lot of work on it so far. However, I won't ultimately be able to contribute this upstream as this repo lacks a license.

Would you consider adding a free-software license to this repo, such as the GPL 3+? 

You'd get full attribution for your work, of course.

**Comment by ryanprior** [comment]
Added in d34598ebfd6853a1278ee564148564c2fb31980c

Thank you for your interest @cdo256! I wish you best of luck with packaging Hugo- I found it to be more than I could handle in two concerted efforts. The golang importer has improved a lot since my last attempt, so I'd start there.

Happy hacking!

**Comment by cdo256** [comment]
Wonderful, thank you!
